Add a pseudo-random number function
panix-os-dev-team/Panix pull request #259
Opened 2021-07-21 04:12 UTC by Jmallone

The pseudorandom number function in `kernel/lib/stdlib.c`  folder.
`rand()` and `srand()`

2021-07-21 20:13 UTC, Kfeavel requested changes
Looks good besides that one define and needing to link to the different resources (OSDev Wiki, C Standard, etc).

2021-07-21 20:13 UTC, Kfeavel commented on kernel/lib/stdlib.hpp
> +#define MAX_RAND 32767
Is this necessary to access outside of the source file? If not, I would move it out of the header.

2021-07-21 21:31 UTC, micahswitzer commented on kernel/lib/stdlib.hpp
> +#define MAX_RAND 32767
POSIX says it should be publicly available

2021-07-21 22:45 UTC, Kfeavel commented on kernel/lib/stdlib.hpp
> +#define MAX_RAND 32767
Awesome, leave it here then. Marking as resolved.

2021-07-21 23:27 UTC, Jmallone commented
nice, i'll change this

2021-07-22 01:50 UTC, Kfeavel commented
@Jmallone I would also rename the files to `rand.hpp` and `rand.cpp` instead of `stdlib.*`.

2021-07-22 03:06 UTC, closed without merging

2021-07-22 03:11 UTC, Kfeavel commented
Closed since @Jmallone couldn't update the MR to point to their new branch.